# Generated by Django 3.1.5 on 2021-02-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_describe', models.CharField(max_length=150, verbose_name='Todo')),
                ('todo_case', models.BooleanField(default=False, verbose_name='Case')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('inserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Inserted By')),
            ],
        ),
    ]
