# Generated by Django 3.1.7 on 2021-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_case_CASE',
            field=models.CharField(choices=[('True', 'Done'), ('False', 'Undone')], default='Ture', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_case',
            field=models.BooleanField(default=False),
        ),
    ]
