# Generated by Django 3.1.7 on 2021-02-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210227_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_case',
        ),
    ]
