# Generated by Django 3.1.7 on 2021-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_todo_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_case_CASE',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_case',
            field=models.CharField(choices=[('True', 'Done'), ('False', 'Undone')], default='False', max_length=10),
        ),
    ]
